### ISSUE TITLE
[Bug] No artwork or previous artwork for songs with no artwork

### ISSUE THREAD

**Issue by TheAwesome98-Real** [minh-ton/NineMusic#2]
If a song (I’m playing ones from Files, I don’t have any in Apple music so I cannot test that ¯\\\_(ツ)_/¯) has no artwork, it displays no artwork instead of the song icon, or if a song with an artwork was played before it, it retains that artwork.

**Comment by minh-ton** [comment]
Do you have a video or a screenshot of your problem?

**Comment by TheAwesome98-Real** [comment]
I’ll take a video just now!

**Comment by TheAwesome98-Real** [comment]
https://imgur.com/a/MvGh9L1

**Comment by minh-ton** [comment]
It's actually a problem with the file that you're playing (missing artwork, etc), and is not a problem of the tweak itself.

**Comment by TheAwesome98-Real** [comment]
Yeah, but why doesn’t it set it to a blank artwork when there’s no artwork? It would be fine, other than this problem where it keeps the previous track’s artwork.
