### ISSUE TITLE
(null)

### ISSUE THREAD

**Issue by TheAwesome98-Real** [minh-ton/NineMusic#3]
![(null) in title and artist](https://user-images.githubusercontent.com/59254971/99907034-730e3f80-2cd2-11eb-9300-ee4a4f692ff0.png)

I just went in Notification Center then this

**Comment by minh-ton** [comment]
Restart your playing app (if it is opening). This usually happens when the tweak fails to get the metadata of the now-playing song, or the song has no metadata at all.

**Comment by TheAwesome98-Real** [comment]
Ah, so it's the fault of iOS Files app and not your tweak? thanks!
