### ISSUE TITLE
No Music Controls

### ISSUE THREAD

**Issue by CivilizedGuide** [minh-ton/NineMusic#5]
The music and volume control aren't showing up, i have an iphone SE 2016 and sometimes the cover art doesn't show up

[https://imgur.com/a/jjpAuVX](url) this is an screenshot of what im refering to

**Comment by minh-ton** [comment]
Hi there, 

NineMusic has been deprecated and I'm no longer supporting it. 
Please use [NineLS](https://github.com/Minh-Ton/NineLS) to get the iOS 9 Music Player instead.

**Comment by CivilizedGuide** [comment]
I installed it and everything works except the slide to unlock, it shows up but sliding doesn’t work

**Comment by minh-ton** [comment]
The slide to unlock feature took advantage of the widget screen, so make sure that you don't have any other tweaks that disable it.
